---
title: "GRAD_DEFAULT_DIFF"
author: "Nathaniel Jones"
output: word_document
---

```{r setup, include=F,echo=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8)
#install.packages("officedown")
#install.packages("officer")
#install.packages("magrittr")
#install.packages("tidyverse") 
#install.packages("ggpubr") 
#install.packages("gplots") 
#install.packages("multcompView") 

library(ggpubr)
library(gplots)
library(multcompView)
library(tidyverse)
library(magrittr)   # piping related. %<>% is "<-" + "and then". both assigns and pipes.
library(officedown) # to change the text colors
library(officer)    # used with officedown
library(perm)
library(jmuOutlier) # source of perm test for median and trimmed means.
library(plyr)       # ddply
ft <- fp_text(color = 'mediumorchid4', bold = TRUE) # change the color of text easily
inline_hook <- function(x) {                # used in making the numbers print in decimal form instead of scientific notation
  if (is.numeric(x)) {
    format(x, digits = 9)
  } else x 
}
knitr::knit_hooks$set(inline = inline_hook) # this makes the numbers not print in scientific notation during inline code.
wrapper <- function(x) {
  round(x,4)
}
```

```{r read in dataset and set the mood, echo=F,echo=F}
# Import the 2018 College Scorecard data and tidy it up.
CollegeSC18 <- read.csv("MERGED2018_19_PP.csv", stringsAsFactors = TRUE, na.strings = c("PrivacySuppressed","NULL","NaN","NA"))
CollegeSC18 <- tibble(CollegeSC18)
#CollegeSC18 %>% head(10)
personal_Palette <- c("#999999","#bae600", "#E6c500", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#CC79A7","mediumpurple","mediumpurple4",
                     "cornflowerblue","magenta3","royalblue4","orchid4","orchid3","orchid1","plum4","turquoise1","turquoise","turquoise4",
                     "violet","plum3","plum1","aquamarine","aquamarine3","aquamarine4","cyan","cyan4","cyan3")
cbPalette <- c("#999999", "#56B4E9", "#009E73", "#0072B2", "#CC79A7")
CollegeSC18 %<>% mutate("PCTPELL_CAT" = ifelse(is.na(PCTPELL)!=T,               # Check if missing. IF not True, THEN continue, ELSE go to **
                                               ifelse(PCTPELL <= .5,0,          # Check Condition One, return 0 if true, 
                                                      1),                       # ELSE return 1
                                               NA))
CollegeSC18$PCTPELL_CAT <- as.factor(CollegeSC18$PCTPELL_CAT)

iters <- 1000000
scalr <- 100
```

```{r functions,include=F}
RMD.test <- function(samp1,samp2,direction=c('two.sided','less','greater')[1],nsamp=10000,nprt=0){
  devs1 <- samp1-median(samp1)
  devs2 <- samp2-median(samp2)
  devs <- c(devs1,devs2)   #concatenates both data sets into one vector
  devs
  
  
  
  RMD <- mean(abs(devs1))/mean(abs(devs2))  #sample RMD
  if (direction[1]=='two.sided'){
    RMD <- max(1/RMD, RMD) #compensates when the smallest mean absolute deviation is on top to make sure that the largest mean absolute deviation is on top for the two.sided test
  }
  RMDperms <- rep(NA,nsamp) #sets up an empty vector of missing values to be filled for the 10,000 permutations

  
  for (i in 1:nsamp){
    tempdevs <- devs[sample(length(devs),length(devs),replace=FALSE)] # inside the square brackets is a sampling command that shuffles the indices 1 to the total number in both samples for the concatenated vector "devs"

    RMDperms[i] <- mean(abs(tempdevs[1:length(devs1)]))/mean(abs(tempdevs[-(1:length(devs1))]))
    if (direction[1]=='two.sided') RMDperms[i] <- max(1/RMDperms[i], RMDperms[i])
  }
  if (direction[1]=='greater') pVal <- mean(RMDperms>=RMD)
  if (direction[1]=='less') pVal <- mean(RMDperms<=RMD)
  if (direction[1]=='two.sided') pVal <- mean(RMDperms>=RMD)
  if (nprt==0) {
  return(c(print(paste("The mean absolute deviation for the data in sample 1 is:", round(mean(abs(devs1)),2) )),
           print(paste("The mean absolute deviation for the data in sample 2 is:", round(mean(abs(devs2)),2) )),
           print(paste("Test statistic:",round(RMD,4))),
           print(paste("Approximate p-value for ",direction[1],":  ",pVal,sep=""))))
  } else {
    return()
  }
}
```

```{r}
######################################################################################################################################################################
##### VARIABLE: OMAWDP8_ALL :: Graduation rate #######################################################################################################################
######################################################################################################################################################################
CSC18 <- CollegeSC18 %>% filter(is.na(PCTPELL)==F,is.na(OMAWDP8_ALL)==F) %>% select(PCTPELL,PCTPELL_CAT,OMAWDP8_ALL,INSTNM)
Cat_var <- CSC18$PCTPELL_CAT
CSC18 %>% summary()

mu <- plyr::ddply(CSC18, "PCTPELL_CAT", summarise, grp.mean=mean(OMAWDP8_ALL))
Zero_data <- subset(CSC18, subset = CSC18$PCTPELL_CAT=="0") # <= 50%
One_data  <- subset(CSC18, subset = CSC18$PCTPELL_CAT=="1") # >  50%

Quant_var <- CSC18$OMAWDP8_ALL    

G0 <- Zero_data$OMAWDP8_ALL
G1 <- One_data$OMAWDP8_ALL




         # RMD test
Ratio_MD <- RMD.test(G0,G1,direction="two.sided",nsamp=iters,nprt=0)
Ratio_MD

         # Parametric t-test
ttst <- stats::t.test(G1,G0,
              alternative= "two.sided",
              mu=0, paired = F, 
              var.equal=F,
              conf.level=.95)
ttst

         # Wilcoxon Rank-sum
wilcox_test <- stats::wilcox.test(G1,G0,conf.int=T,
                                  alternative="two.sided",conf.level=.95)
wilcox_test

         # Permutation test for the difference in means
perm_Mean <- permTS(G1,G0,
                    method = "exact.mc",
                    alternative = "two.sided",
                    control=permControl(nmc=iters,seed=59911402))
perm_Mean
observed_test_stat_mean <- abs(mean(G1)-mean(G0))

diff_mean <- rep(NA,iters)

for (i in 1:iters){
  all_values <- c(G1,G0)
  shuffles <- sample(all_values,length(all_values),replace=FALSE)
  diff_mean[i] <- abs(mean(shuffles[1:50])-mean(shuffles[51:100]))
}

perm_mean_hist <- hist(diff_mean, 
                       cex.lab=1.5, 
                       cex.axis=1.5,
                       cex.main=1.5)
perm_mean_hist
p_value_mean <- mean(diff_mean >= observed_test_stat_mean)
p_value_mean

         # Permutation test for the difference in medians
observed_test_stat_median <- abs(median(G1)-median(G0))

difmeds <- rep(NA,iters)

for (i in 1:iters){
  all_values <- c(G1,G0)
  shuffles <- sample(all_values,length(all_values),replace=FALSE)
  difmeds[i] <- abs(median(shuffles[1:50])-median(shuffles[51:100]))
}

perm_median_hist <- hist(difmeds,
                         cex.lab=1.5, #changes the size of BOTH word labels for the x and y axes
                         cex.axis=1.5,
                         cex.main=1.5)

p_value <- mean(difmeds >= observed_test_stat_median)
p_value
```

```{r }
ggplot(CSC18, aes(x=OMAWDP8_ALL,fill=PCTPELL_CAT)) + geom_histogram(aes(y=stat(count)/sum(count),fill=PCTPELL_CAT),color="black",binwidth=.07) +
  scale_x_continuous(breaks=seq(0,1,.07)) + scale_y_continuous(labels=scales::percent) +
  scale_fill_manual(name="group",values=c("springgreen","cadetblue2"),labels=c("0 - Pell Recipients (<=50%)","1 - Pell Recipients (>50%)"))+
       facet_grid(PCTPELL_CAT ~ .) + xlab("Percentage of all student receiving an award within 8 years of entry.(OMAWDP8_ALL)") +
       labs(title= "Figure 1: Histogram of the Percentage of all student receiving an award within 8 years of entry stratified by the categories of PCTPELL_CAT. (n = 5065)") +
       geom_vline(data=mu, aes(xintercept=grp.mean, color=PCTPELL_CAT),
                  linetype="dashed",lwd=1.1,show.legend = F) +
       stat_bin(aes(y=..count../sum(..count..),label=paste(round(..count../sum(..count..),4)*100,"%",sep=" ")),binwidth=.07, geom="text",vjust=-.5)

boxplot(Quant_var~Cat_var,
        names=c("0 - Pell Recipients (<=50%)","1 - Pell Recipients (>50%)"), 
        main="Figure 2: Boxplot of the percent of students who graduated with an award within 8 years stratified by the categories of PCTPELL_CAT. (n = 5065)", 
        boxwex=0.4, 
        xlab="PCTPELL_CAT", 
        ylab="OMAWDP8_ALL",
        cex.lab=1.5,
        cex.main=1,
        cex.axis=1.5,
        col=sample(personal_Palette,2)
        )

# Plot the mean point
points(2,mean(G1),pch=7)
points(1,mean(G0),pch=7)

# For the leftside boxplot
text(y = boxplot.stats(G0)$stats, 
     labels = paste(((boxplot.stats(G0)$stats)*100),"%",sep=" "), 
     x = 1.34, 
     cex = 1.5)
text(y = round(min(G0),3), 
     labels = paste((round(min(G0),3)*100),"%",sep=" "),
     x = 1.34, 
     cex = 1.5)
text(y = round(max(G0),3), 
     labels = paste((round(max(G0),3)*100),"%",sep=" "), 
     x =  1.34, 
     col = "black", 
     cex  =1.5)
text(y = round(mean(G0),3), 
     labels = paste((round(mean(G0),3)*100),"%",sep=" "),
     x = 0.67,
     cex = 1.5)

# For the rightside boxplot
text(y = boxplot.stats(G1)$stats, 
     labels = paste(((boxplot.stats(G1)$stats)*100),"%",sep=" "), 
     x = 2.33, 
     col = "black",
     cex = 1.5)
text(y = round(mean(G1),3), # leftside 60%
     labels = paste((round(mean(G1),3)*100),"%",sep=" "), 
     x = 1.67,
     col = "black",
     cex = 1.5)
text(y = round(max(G1),3), 
     labels = paste((round(max(G1),3)*100),"%",sep=" "), 
     x =  2.33, 
     col = "black", 
     cex  =1.5)
text(y = round(min(G1),3), 
     labels = paste((round(min(G1),3)*100),"%",sep=" "),
     x = 2.33, 
     col = "black", 
     cex = 1.5)

# QQ plot
qqnorm(G0,main="Figure 3.A: Q-Q plot for GRAD_RATE: G0",pch=19,cex.main=.83)
qqline(G0,col = "steelblue")
abline(v = 0, col="red")

# QQ plot
qqnorm(G1,main="Figure 3.B: Q-Q plot for GRAD_RATE: G1",pch=19,cex.main=.84)
qqline(G1,col = "steelblue")
abline(v = 0, col="red")

plot(perm_mean_hist,col="cadetblue1",xlim=c(0,.3),main="Histogram for the permutation test on the difference in mean")
abline(v=observed_test_stat_mean,col="blue",lty=1, lwd=5)
text(observed_test_stat_mean + observed_test_stat_mean*.178, 1525*scalr, paste("Observed Test statistic of ",round(observed_test_stat_mean,4),sep=""))
rect(observed_test_stat_mean,0,.3,1500*scalr,col=alpha("red",0))
text(.26, 975*scalr, "Difference in mean")
text(.26, 913*scalr, "greater than or equal")
text(.26, 848*scalr, "to the observed difference")

plot(perm_median_hist,col="cadetblue1",main="Histogram for the permutation test on the difference in median",xlim=c(0,.35))
abline(v=observed_test_stat_median,col="blue",lty=1, lwd=5)
text(observed_test_stat_median + observed_test_stat_median*.178, 2452*scalr, paste("Observed Test statistic of ",observed_test_stat_median,sep=""))
rect(observed_test_stat_median,0,.35,2400*scalr,col=alpha("red",0))
text(.29, 1500*scalr, "Difference in medians")
text(.29, 1433*scalr, "greater than or equal")
text(.29, 1369*scalr, "to the observed difference")


```

```{r ,echo=F}
######################################################################################################################################################################
##### VARIABLE: BBRR2_FED_UG_DFLT :: Default rate ####################################################################################################################
######################################################################################################################################################################
CSC18 <- CollegeSC18 %>% filter(is.na(PCTPELL)==F,is.na(BBRR2_FED_UG_DFLT)==F) %>% select(PCTPELL,PCTPELL_CAT,BBRR2_FED_UG_DFLT)
Cat_var <- CSC18$PCTPELL_CAT
CSC18 %>% summary()

mu <- plyr::ddply(CSC18, "PCTPELL_CAT", summarise, grp.mean=mean(BBRR2_FED_UG_DFLT))
Zero_data <- subset(CSC18, subset = CSC18$PCTPELL_CAT=="0") # <= 50%
One_data  <- subset(CSC18, subset = CSC18$PCTPELL_CAT=="1") # >  50%



Quant_var <- CSC18$BBRR2_FED_UG_DFLT

G0 <- Zero_data$BBRR2_FED_UG_DFLT
G1 <- One_data$BBRR2_FED_UG_DFLT



         # RMD test
Ratio_MD <- RMD.test(G0,G1,direction="two.sided",nsamp=iters,nprt=0)
Ratio_MD

         # Parametric t-test
ttst <- stats::t.test(G1,G0,
              alternative= "two.sided",
              mu=0, paired = F, 
              var.equal=F,
              conf.level=.95)
ttst

         # Wilcoxon Rank-sum
wilcox_test <- stats::wilcox.test(G1,G0,conf.int=T,
                                  alternative="two.sided",conf.level=.95)
wilcox_test

         # Permutation test for the difference in means
perm_Mean <- permTS(G1,G0,
                    method = "exact.mc",
                    alternative = "two.sided",
                    control=permControl(nmc=iters,seed=59911402))
perm_Mean
observed_test_stat_mean <- abs(mean(G1)-mean(G0))

diff_mean <- rep(NA,iters)

for (i in 1:iters){
  all_values <- c(G1,G0)
  shuffles <- sample(all_values,length(all_values),replace=FALSE)
  diff_mean[i] <- abs(mean(shuffles[1:50])-mean(shuffles[51:100]))
}

perm_mean_hist <- hist(diff_mean, 
                       cex.lab=1.5, 
                       cex.axis=1.5,
                       cex.main=1.5)
perm_mean_hist
p_value_mean <- mean(diff_mean >= observed_test_stat_mean)
p_value_mean


         # Permutation test for the difference in medians
observed_test_stat_median <- abs(median(G1)-median(G0))

difmeds <- rep(NA,iters)

for (i in 1:iters){
  all_values <- c(G1,G0)
  shuffles <- sample(all_values,length(all_values),replace=FALSE)
  difmeds[i] <- abs(median(shuffles[1:50])-median(shuffles[51:100]))
}

perm_median_hist <- hist(difmeds,
                         cex.lab=1.5, #changes the size of BOTH word labels for the x and y axes
                         cex.axis=1.5,
                         cex.main=1.5)
perm_median_hist
p_value <- mean(difmeds >= observed_test_stat_median)
p_value


```

```{r}
ggplot(CSC18, aes(x=BBRR2_FED_UG_DFLT,fill=PCTPELL_CAT)) + geom_histogram(aes(y=stat(count)/sum(count),fill=PCTPELL_CAT),color="black",binwidth=.034) +
  scale_x_continuous(breaks=seq(0,1,.034)) + scale_y_continuous(labels=scales::percent) +
  scale_fill_manual(name="group",values=c("springgreen","cadetblue2"),labels=c("0 - Pell Recipients (<=50%)","1 - Pell Recipients (>50%)"))+
       facet_grid(PCTPELL_CAT ~ .) + xlab("Percentage of BBRR2_FED_UG_DFLT.(BBRR2_FED_UG_DFLT)") +
       labs(title= "Figure 1: Histogram of BBRR2_FED_UG_DFLT stratified by the categories of PCTPELL_CAT. (n = 5065)") +
       geom_vline(data=mu, aes(xintercept=grp.mean, color=PCTPELL_CAT),
                  linetype="dashed",lwd=1.1,show.legend = F) +
       stat_bin(aes(y=..count../sum(count),label=paste(round(..count../sum(..count..),4)*100,"%",sep=" ")),binwidth=.034, geom="text",vjust=-.5)

boxplot(Quant_var~Cat_var,
        names=c("0 - Pell Recipients (<=50%)","1 - Pell Recipients (>50%)"), 
        main="Figure 2: Boxplot of BBRR2_FED_UG_DFLT stratified by the categories of PCTPELL_CAT. (n = 5065)", 
        boxwex=0.4, 
        xlab="PCTPELL_CAT", 
        ylab="BBRR2_FED_UG_DFLT",
        cex.lab=1.5,
        cex.main=1,
        cex.axis=1.5,
        col=sample(personal_Palette,2)
        )

# Plot the mean point
points(2,mean(G1),pch=7)
points(1,mean(G0),pch=7)

# For the leftside boxplot
text(y = boxplot.stats(G0)$stats, 
     labels = paste(round(boxplot.stats(G0)$stats*100,2),"%",sep=" "), 
     x = 1.34, 
     cex = 1.5)
#text(y = round(min(G0),3), 
#     labels = paste((round(min(G0),3)*100),"%",sep=" "),
#     x = 1.34, 
#     cex = 1.5)
text(y = round(max(G0),3), 
     labels = paste((round(max(G0),3)*100),"%",sep=" "), 
     x =  1.34, 
     col = "black", 
     cex  =1.5)
text(y = round(mean(G0),3), 
     labels = paste((round(mean(G0),3)*100),"%",sep=" "),
     x = 0.67,
     cex = 1.5)

# For the rightside boxplot
text(y = boxplot.stats(G1)$stats, 
     labels = paste(round(boxplot.stats(G1)$stats*100,2),"%",sep=" "), 
     x = 2.33, 
     col = "black",
     cex = 1.5)
text(y = round(mean(G1),3), # leftside 60%
     labels = paste((round(mean(G1),3)*100),"%",sep=" "), 
     x = 1.67,
     col = "black",
     cex = 1.5)
text(y = round(max(G1),3), 
     labels = paste((round(max(G1),3)*100),"%",sep=" "), 
     x =  2.33, 
     col = "black", 
     cex  =1.5)
#text(y = round(min(G1),3), 
#     labels = paste((round(min(G1),3)*100),"%",sep=" "),
#     x = 2.33, 
#     col = "black", 
#     cex = 1.5)

# QQ plot
qqnorm(G0,main="Figure 3.A: Q-Q plot for STAT_UNK: G0",pch=19,cex.main=.83)
qqline(G0,col = "steelblue")
abline(v = 0, col="red")

# QQ plot
qqnorm(G1,main="Figure 3.B: Q-Q plot for STAT_UNK: G1",pch=19,cex.main=.84)
qqline(G1,col = "steelblue")
abline(v = 0, col="red")


plot(perm_mean_hist,col="cadetblue1",xlim=c(0,.3),main="Histogram for the permutation test on the difference in mean")
abline(v=observed_test_stat_mean,col="blue",lty=1, lwd=5)
text(observed_test_stat_mean - observed_test_stat_mean*.178, 1525*scalr, paste("Observed Test statistic of ",round(observed_test_stat_mean,4),sep=""))
rect(observed_test_stat_mean,0,.3,1500*scalr,col=alpha("red",0))
text(.26, 975*scalr, "Difference in mean")
text(.26, 913*scalr, "greater than or equal")
text(.26, 848*scalr, "to the observed difference")

plot(perm_median_hist,col="cadetblue1",main="Histogram for the permutation test on the difference in median",xlim=c(0,.35))
abline(v=observed_test_stat_median,col="blue",lty=1, lwd=5)
text(observed_test_stat_median - observed_test_stat_median*.178, 2452*scalr, paste("Observed Test statistic of ",observed_test_stat_median,sep=""))
rect(observed_test_stat_median,0,.35,2400*scalr,col=alpha("red",0))
text(.29, 1500*scalr, "Difference in medians")
text(.29, 1433*scalr, "greater than or equal")
text(.29, 1369*scalr, "to the observed difference")
```

```{r Subsetting GRAD rate}
CollegeSC18 %<>% mutate("GRAD_CAT" = ifelse(is.na(OMAWDP8_ALL),NA,
                                            ifelse(OMAWDP8_ALL<.3,0,
                                                   ifelse(OMAWDP8_ALL>.65,2,1))))
CollegeSC18$GRAD_CAT <- as.factor(CollegeSC18$GRAD_CAT)
CollegeSC18 %>% select(GRAD_CAT) %>% summary()
```
```{r}
#Keeper stories:
#  Uni that have a higher grad rate within 8 years associated with lower default rate
######################################################################################################################################################################
##### VARIABLE: BBRR2_FED_UG_DFLT :: Default rate by Graduation rate Categories ######################################################################################
######################################################################################################################################################################
CSC18 <- CollegeSC18 %>% filter(is.na(GRAD_CAT)==F) %>% filter(is.na(BBRR2_FED_UG_DFLT)==F) %>% select(PCTPELL,PCTPELL_CAT,GRAD_CAT,BBRR2_FED_UG_DFLT)
Cat_var <- CSC18$GRAD_CAT
CSC18 %>% summary()

ada <- plyr::ddply(CSC18, "GRAD_CAT", summarise, grp.median=median(BBRR2_FED_UG_DFLT))
Zero_data <- subset(CSC18, subset = CSC18$GRAD_CAT=="0") # <  30%
One_data  <- subset(CSC18, subset = CSC18$GRAD_CAT=="1") # >= 30%
Two_data  <- subset(CSC18, subset = CSC18$GRAD_CAT=="2") # >  65%

Quant_var <- CSC18$BBRR2_FED_UG_DFLT

G0 <- Zero_data$BBRR2_FED_UG_DFLT
G1 <- One_data$BBRR2_FED_UG_DFLT
G2 <- Two_data$BBRR2_FED_UG_DFLT

ggplot(CSC18, aes(x=BBRR2_FED_UG_DFLT,fill=GRAD_CAT)) + geom_histogram(aes(y=stat(count),fill=GRAD_CAT),color="black",binwidth=.034) +
  scale_x_continuous(breaks=seq(0,1,.034)) + #scale_y_continuous(labels=scales::percent) +
  scale_fill_manual(name="group",values=sample(personal_Palette,3),labels=c("< 30%",">= 30% <= 65%","> 65%"))+
       facet_grid(GRAD_CAT ~ PCTPELL_CAT) + xlab("Percentage of BBRR2_FED_UG_DFLT.(BBRR2_FED_UG_DFLT)") +
       labs(title= "Figure 1: Histogram of BBRR2_FED_UG_DFLT stratified by the categories of GRAD_CAT. (n = 5065)") +
       geom_vline(data=ada, aes(xintercept=grp.median, color=GRAD_CAT),
                  linetype="dashed",lwd=1.1,show.legend = F) +
       stat_bin(aes(y=..count..,label=paste(..count..,sep=" ")),binwidth=.034, geom="text",vjust=-.5)

boxplot(Quant_var~Cat_var,
        names=c("< 30%",">= 30% <= 65%","> 65%"), 
        main="Figure 2: Boxplot of BBRR2_FED_UG_DFLT stratified by the categories of GRAD_CAT. (n = 5065)", 
        boxwex=0.4, 
        xlab="GRAD_CAT", 
        ylab="BBRR2_FED_UG_DFLT",
        cex.lab=1.5,
        cex.main=1,
        cex.axis=1.5,
        col=sample(personal_Palette,2)
        )

# Plot the mean point
points(2,mean(G1),pch=7)
points(1,mean(G0),pch=7)

# For the leftside boxplot
text(y = boxplot.stats(G0)$stats, 
     labels = paste(round(boxplot.stats(G0)$stats*100,2),"%",sep=" "), 
     x = 1.34, 
     cex = 1.5)
#text(y = round(min(G0),3), 
#     labels = paste((round(min(G0),3)*100),"%",sep=" "),
#     x = 1.34, 
#     cex = 1.5)
text(y = round(max(G0),3), 
     labels = paste((round(max(G0),3)*100),"%",sep=" "), 
     x =  1.34, 
     col = "black", 
     cex  =1.5)
text(y = round(mean(G0),3), 
     labels = paste((round(mean(G0),3)*100),"%",sep=" "),
     x = 0.67,
     cex = 1.5)

# For the middle boxplot
text(y = boxplot.stats(G1)$stats, 
     labels = paste(round(boxplot.stats(G1)$stats*100,2),"%",sep=" "), 
     x = 2.33, 
     col = "black",
     cex = 1.5)
text(y = round(mean(G1),3), # leftside 60%
     labels = paste((round(mean(G1),3)*100),"%",sep=" "), 
     x = 1.67,
     col = "black",
     cex = 1.5)
text(y = round(max(G1),3), 
     labels = paste((round(max(G1),3)*100),"%",sep=" "), 
     x =  2.33, 
     col = "black", 
     cex  =1.5)
#text(y = round(min(G1),3), 
#     labels = paste((round(min(G1),3)*100),"%",sep=" "),
#     x = 2.33, 
#     col = "black", 
#     cex = 1.5)

# For the rightside boxplot
text(y = boxplot.stats(G2)$stats, 
     labels = paste(round(boxplot.stats(G2)$stats*100,2),"%",sep=" "), 
     x = 3.33, 
     col = "black",
     cex = 1.5)
text(y = round(mean(G2),3), # leftside 60%
     labels = paste((round(mean(G2),3)*100),"%",sep=" "), 
     x = 2.67,
     col = "black",
     cex = 1.5)
text(y = round(max(G2),3), 
     labels = paste((round(max(G2),3)*100),"%",sep=" "), 
     x =  3.33, 
     col = "black", 
     cex  =1.5)
#text(y = round(min(G2),3), 
#     labels = paste((round(min(G2),3)*100),"%",sep=" "),
#     x = 2.33, 
#     col = "black", 
#     cex = 1.5)

# QQ plot
qqnorm(G0,main="Figure 3.A: Q-Q plot for Default rate: G0",pch=19,cex.main=.83)
qqline(G0,col = "steelblue")
abline(v = 0, col="red")

# QQ plot
qqnorm(G1,main="Figure 3.B: Q-Q plot for STAT_UNK: G1",pch=19,cex.main=.84)
qqline(G1,col = "steelblue")
abline(v = 0, col="red")

# QQ plot
qqnorm(G2,main="Figure 3.B: Q-Q plot for STAT_UNK: G2",pch=19,cex.main=.84)
qqline(G1,col = "steelblue")
abline(v = 0, col="red")


```

```{r Testing Equality of Variances FUNCTION}
# Call Statement for the Function to check if the ratio of the largest standard deviation to the smalles standard deviation is less than 2, the rule of thumb for being able to pool.
# Function
Ratio_of_MaxToMin_SD <- function(quant,categ){
  temp<-tapply(quant,categ,FUN=sd)
  ratio<-round(max(temp)/min(temp),2)
  return(temp)
}

Ratio_of_MaxToMin_SD(quant=Quant_var,categ=Cat_var)
```

```{r}
plotmeans(Quant_var~Cat_var, ylim=c(0.05,.15),
          use.t=TRUE,
          digits=2, 
          bars=TRUE,            # conf int bars
          barcol="blue",
          p=.95, 
          mean.labels=TRUE, 
          n.label=TRUE, 
          ci.label=TRUE,
          connect=TRUE,
          ccol="red",     
          main="Plot of the defualt rate by graduation rate categories",
          ylab="Percent of students in default after 2 years",
          xlab="< 30%,>= 30% <= 50%,< 65,> 65%",
          cex.main=1.5, cex.lab=1, cex.axis=1.5)
```

```{r}

```










